@url = http://localhost:4000

GET {{url}}/user

###

POST {{url}}/user/register 
Content-Type: application/json

{
    "username": "momYay4<>",
    "email": "socksStuffmore@aol.com"
}

###
POST {{url}}/user/login
Content-Type: application/json

{
    "username": "momYay4<>",
    "email": "socksStuffmore@aol.com"
}

###
GET {{url}}/articles

###
POST {{url}}/articles
Content-Type: application/json

{
    "heading": "random stuff",
    "content": ["Liquorice pie marshmallow powder liquorice cheesecake jelly chocolate bar macaroo"],
    "photoUrl": "https://cdn.stocksnap.io/img-thumbs/960w/woman-skin_3AECYIAEDE.jpg",
    "author": "Summer beauty tips",
    "topic": "beauty"
    
   
}

###
DELETE {{url}}/articles/62a700e74081eae43683a896

###
PATCH {{url}}/articles/62a8a699d30c6054de0a5782
Content-Type: application/json

{
    "photoUrl": "https://cdn.stocksnap.io/img-thumbs/960w/woman-skin_IG8R5XE2WD.jpg"
}

